[phases.setup]
nixPkgs = ["nodejs_22", "python3", "pkg-config", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["[ -d client ] && cd client && npm install && npm run build || echo 'No client folder, skipping React build'"]

[start]
cmd = "node server.js"